name: Compiling papers - Tests
on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'URL of the repository containing the paper file'
        required: true
      branch:
        description: 'Git branch where the paper Markdown file is'
        required: false

jobs:
  compiling:
    runs-on: ubuntu-latest
    steps:
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true
      - name:
        env:
          REPO_URL: ${{ github.event.inputs.repository_url }}
          PAPER_BRANCH: ${{ github.event.inputs.branch }}
        run: |
          echo $REPO_URL
          echo $PAPER_BRANCH
