name: Compiling papers - Tests
on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'URL of the repository containing the paper file'
        required: true
      branch:
        description: 'Git branch where the paper Markdown file is'
        required: false
      issue_id:
        description: 'Git branch where the paper Markdown file is'
        required: false

jobs:
  compiling:
    runs-on: ubuntu-latest
    steps:
      - name: Compile Paper
        id: generate-pdf
        uses: xuanxu/compiler-action-testing@main
        with:
          repository_url: ${{ github.event.inputs.repository_url }}
          branch: ${{ github.event.inputs.branch }}
          journal: joss
      - name: Upload file to papers repo
        uses: xuanxu/upload-paper-action@main
        with:
          papers_repo: aliadalabs/papers-test
          branch_prefix: joss
          issue_id: ${{ github.event.inputs.issue_id }}
          pdf_path: ${{ steps.generate-pdf.outputs.paper_pdf_path}}
