name: Compiling papers - Tests
on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'URL of the repository containing the paper file'
        required: true
      branch:
        description: 'Git branch where the paper Markdown file is'
        required: false
      issue_id:
        description: 'The issue number of the submission'
        required: true

jobs:
  compiling:
    runs-on: ubuntu-latest
    steps:
      - name: Compile Paper
        id: generate-pdf
        uses: xuanxu/compiler-action-testing@main
        with:
          repository_url: ${{ github.event.inputs.repository_url }}
          branch: ${{ github.event.inputs.branch }}
          journal: joss
      - name: Upload file to papers repo
        id: upload-pdf
        uses: xuanxu/upload-paper-action@test
        with:
          papers_repo: aliadalabs/papers-test
          branch_prefix: joss
          issue_id: ${{ github.event.inputs.issue_id }}
          pdf_path: ${{ steps.generate-pdf.outputs.pdf_path}}
          bot_token: ${{ secrets.PDF_BOT_TOKEN }}
      - name: Reply message
        if: ${{ success() }}
        run: |
          gh issue comment ${{ github.event.inputs.issue_id }} --body ":point_right::page_facing_up: [Download article proof](${{ steps.upload-pdf.outputs.download_url}}) :page_facing_up: [View article proof on GitHub](${{ steps.upload-pdf.outputs.html_url}}) :page_facing_up: :point_left:"
        env:
          GITHUB_TOKEN: ${{ secrets.PDF_BOT_TOKEN }}
      - name: Error message
        if: ${{ failure() }}
        run: echo "FAIL"
