name: Compiling papers - Tests
on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'URL of the repository containing the paper file'
        required: true
      branch:
        description: 'Git branch where the paper Markdown file is'
        required: false

jobs:
  compiling:
    runs-on: ubuntu-latest
    steps:
      - name: Find Paper
        id: find-paper
        uses: xuanxu/compiler-action-testing@main
        with:
          repository_url: ${{ github.event.inputs.repository_url }}
          branch: ${{ github.event.inputs.branch }}
          journal: joss
      - name: Test
        run: |
          echo "Testing outputs"
          echo $(ls -la ./target_repository/paper/)