name: Compiling papers - Tests
on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'URL of the repository containing the paper file'
        required: true
      branch:
        description: 'Git branch where the paper Markdown file is'
        required: false

jobs:
  cloning-repo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Cloning ${{ github.event.inputs.repository_url }}"
          echo "- using branch ${{ github.event.inputs.branch }}"
          echo "- file located: ${{ github.event.inputs.paper_path }}"
