name: Deposit Dry Run
on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'URL of the repository containing the paper file'
        required: true
      branch:
        description: 'Git branch where the paper Markdown file is'
        required: false
      issue_id:
        description: 'The issue number of the submission'
        required: true

jobs:
  preparing-acceptance:
    runs-on: ubuntu-latest
    steps:
      - name: Compile Paper
        id: generate-pdf
        uses: xuanxu/compile-paper-action@main
        with:
          repository_url: ${{ github.event.inputs.repository_url }}
          branch: ${{ github.event.inputs.branch }}
          journal: joss
      - name: Upload file to papers repo
        id: upload-pdf
        uses: xuanxu/upload-paper-action@main
        with:
          papers_repo: aliadalabs/papers-test
          branch_prefix: joss
          issue_id: ${{ github.event.inputs.issue_id }}
          pdf_path: ${{ steps.generate-pdf.outputs.pdf_path}}
          bot_token: ${{ secrets.PDF_BOT_TOKEN }}
      # - name: Add Crossref data
      #   id: upload-xml
      #   uses: xuanxu/upload-crossref-action@main
      #   with:
      #     papers_repo: aliadalabs/papers-test
      #     branch_prefix: joss
      #     issue_id: ${{ github.event.inputs.issue_id }}
      #     pdf_path: ${{ steps.generate-pdf.outputs.pdf_path}}
      #     bot_token: ${{ secrets.PDF_BOT_TOKEN }}
      - name: Open Pull Request
        id: open-pr
        uses: xuanxu/deposit-pull-request-action@main
        with:
          papers_repo: aliadalabs/papers-test
          branch_prefix: joss
          issue_id: ${{ github.event.inputs.issue_id }}
          bot_token: ${{ secrets.PDF_BOT_TOKEN }}
          mode: dry-run
      - name: Reply message
        if: ${{ success() }}
        run: |
          gh issue comment ${{ github.event.inputs.issue_id }} --body ":wave: @xuanxu, this paper is ready to be accepted and published.

          Check final proof :point_right: ${{ steps.open-pr.outputs.pr_url}}

          If the paper PDF and Crossref deposit XML look good in ${{ steps.open-pr.outputs.pr_url}}, then you can now move forward with accepting the submission by compiling again with the command \`@botsci publish paper\`"
        env:
          GITHUB_TOKEN: ${{ secrets.PDF_BOT_TOKEN }}
          GH_REPO: ${{ github.repository }}
      - name: Error message
        if: ${{ failure() }}
        run: |
          gh issue comment ${{ github.event.inputs.issue_id }} --body ":warning: [An error happened](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}?check_suite_focus=true)."
        env:
          GITHUB_TOKEN: ${{ secrets.PDF_BOT_TOKEN }}
          GH_REPO: ${{ github.repository }}