name: Paper checks
on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'URL of the repository where the paper file is'
        required: true
      branch:
        description: 'Git branch with the paper file'
        required: false
      issue_id:
        description: 'The issue number of the submission to post the results'
        required: true
      wordcount:
        description:  'Count the number of words in the paper file'
        required: false
        default: true
      statement_of_need:
        description:  'Look for an Statement Of Need section in the paper content'
        required: false
        default: true
jobs:
  read-paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repository }}
      - name: install CLOC
        run: sudo apt install cloc
      - name: run CLOC
        run: cloc --quiet --report-file=cloc-results.txt ${{ github.workspace }} 
      - name: Post results
        run: |
          echo -e "```\n$(cat cloc-results.txt)" > cloc-results.txt
          echo "\n```" >> cloc-results.txt
          gh issue comment ${{ github.event.inputs.issue_id }} --body-file cloc-results.txt
        env:
          GITHUB_TOKEN: ${{ secrets.PDF_BOT_TOKEN }}
          GH_REPO: ${{ github.repository }}
      
